project_id = "sqcituulcofjekcvyfme"

[functions.create-package-checkout]
verify_jwt = false

[functions.create-care-plan-checkout]
verify_jwt = false

[functions.create-verification-checkout]
verify_jwt = false

[functions.verify-vat]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.admin-get-submissions]
verify_jwt = false

[functions.admin-mark-read]
verify_jwt = false

[functions.admin-delete-submission]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false

[functions.admin-update-order-status]
verify_jwt = false
